### ISSUE TITLE
add usage limit

### ISSUE THREAD

**Issue by raspberri05** [personafm/persona.fm#186]
5 per day

**Comment by mashazyu** [comment]
Hello @raspberri05 ,

I'd like to work on this issue, if it's available.

**Comment by raspberri05** [comment]
I went ahead and assigned you to this issue. Feel free to submit your changes via pull request once you are ready. Also, please consider starring this repository as it will enable more developers to find and contribute to this project.

Each user on the platform should be allowed to generate up to 5 personas per day. There is no specific way this needs to be implemented, any way that you come up with works. Please let me know if you have any questions!

**Comment by mashazyu** [comment]
@raspberri05, hello!

Thank you for the opportunity to work on the issue. I appreciate your trust in me to contribute to the project. However, due to personal reasons, I regret to inform you that I will not be able to continue working on this task.
I apologize for any confusion this may cause, and I kindly ask if you could unassign me from the issue.
Thank you for your understanding!
